// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IaKqA_5ilgM70B6gp3IMmBKtBzKB8ws',
    appId: '1:1067855297704:web:9db46ff75b326b58bed69d',
    messagingSenderId: '1067855297704',
    projectId: 'kahveninaski',
    authDomain: 'kahveninaski.firebaseapp.com',
    storageBucket: 'kahveninaski.appspot.com',
    measurementId: 'G-N3H5GZMW0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60PQ_gq1RNwCs53awvk68KZWznqjuAkM',
    appId: '1:1067855297704:android:24d9ea30c5fce6e8bed69d',
    messagingSenderId: '1067855297704',
    projectId: 'kahveninaski',
    storageBucket: 'kahveninaski.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxatVzjov_wo41u9nIakM7v-1NqYYA-M',
    appId: '1:1067855297704:ios:e6ef7080c0127c32bed69d',
    messagingSenderId: '1067855297704',
    projectId: 'kahveninaski',
    storageBucket: 'kahveninaski.appspot.com',
    iosBundleId: 'com.example.kahveninAski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjxatVzjov_wo41u9nIakM7v-1NqYYA-M',
    appId: '1:1067855297704:ios:ed35307a92b96290bed69d',
    messagingSenderId: '1067855297704',
    projectId: 'kahveninaski',
    storageBucket: 'kahveninaski.appspot.com',
    iosBundleId: 'com.example.kahveninAski.RunnerTests',
  );
}
